[build]
  publish = "public"
  command = "git submodule update --init --recursive && npm install && npm run build:css && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.123.0"
  NODE_VERSION = "20.11.0"
